"""Reproducible prepared-source identities; verification never mutates inputs.

Refresh accepts only the reviewed operational delta against an exact predecessor.
Both generated manifests must be published in one Git commit before verification.
No policy or market authority is generated by this module.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
REVIEWED_BASE = '23f06ed84e5b5e2d4efd074618ab44ae7ed58011'
ALLOWED_RUNTIME = frozenset({
    'meme_machine/solana_retention_outcome.py',
    'tests/test_retention_outcomes.py',
    'meme_machine/solana_evidence_plane.py',
    'meme_machine/solana_evidence_service.py',
    'meme_machine/solana_evidence_control.py',
    'meme_machine/solana_archive_snapshot.py',
    'meme_machine/solana_checkpoint.py',
    'tests/test_checkpoint_handoff.py',
    'tests/test_archive_pipeline.py',
    'tests/evidence_stream_harness.py',
    'tests/test_run369_runtime.py',
    'tests/test_coordinated_database.py',
    'tests/test_run381_retention_progress.py',
    'tests/test_run381_maintenance_overlap.py',
})
FROZEN_PRESSURE = (
    'certification/run381_pressure.py',
    'certification/pressure_diagnostics.py',
    'tests/test_run380_production_pressure.py',
    'tests/test_run373_dispatch_throughput.py',
    'certification/tests/fixtures/run380-production-templates.json.gz',
)


def git(*args, cwd=ROOT):
    return subprocess.check_output(['git', *args], cwd=cwd)


def indexed_files(path):
    if git('diff', '--binary', '--no-ext-diff', cwd=path):
        raise ValueError('build_unstaged_native_source')
    extras = git('ls-files', '--others', '-z', cwd=path).decode().split('\0')
    for name in filter(None, extras):
        p = Path(name)
        if (p.suffix in ('.py', '.pyw', '.so', '.pyd', '.pth')
                or p.suffix == '.pyc' and '__pycache__' not in p.parts
                or name in ('.env', 'config.local.json')):
            raise ValueError('build_untracked_native_source:' + name)
    result = {}
    for row in git('ls-files', '--stage', '-z', cwd=path).decode().split('\0'):
        if not row:
            continue
        info, name = row.split('\t', 1)
        mode, checksum, stage = info.split()
        if stage != '0':
            raise ValueError('build_unmerged_native_source:' + name)
        result[name] = (mode, checksum)
    return result


def reviewed_delta(before, after, allowed):
    changed = sorted(name for name in before.keys() | after.keys()
                     if before.get(name) != after.get(name))
    forbidden = set(changed) - set(allowed)
    if forbidden:
        raise ValueError('build_unreviewed_native_delta:' + ','.join(sorted(forbidden)))
    for name in changed:
        if name not in after or after[name][0] not in ('100644', '100755'):
            raise ValueError('build_invalid_native_file:' + name)
    return changed


def diff_identity(path):
    raw = git('diff', '--binary', '--full-index', '--no-ext-diff',
              '--no-textconv', '--no-renames', '--cached', 'HEAD', cwd=path)
    return hashlib.sha256(raw).hexdigest()


def refresh_composed_hashes(row, original, native):
    """Keep the existing strategy-hash key set; refresh only reviewed old pins.

    Integration overlays already have two independent executable bindings:
    exact committed root bytes and the complete staged native diff identity.
    Adding their names to the strategy hash map changes its semantic contract.
    """
    composed = row.setdefault('composed_file_hashes', {})
    old = original.get('composed_file_hashes', {})
    for rel in ALLOWED_RUNTIME:
        if rel not in old:
            composed.pop(rel, None)
        elif rel in row.get('integration_overlay_files', []):
            composed[rel] = hashlib.sha256((Path(native)/rel).read_bytes()).hexdigest()


def refresh(worktrees, baseline_worktrees):
    sources_path = ROOT/'certification/sources.json'
    protocol_path = ROOT/'certification/profitability_protocol.json'
    original = json.loads(git('show', REVIEWED_BASE + ':certification/sources.json'))
    previous_protocol = json.loads(git('show', REVIEWED_BASE + ':certification/profitability_protocol.json'))
    sources = json.loads(sources_path.read_text())
    protocol = json.loads(protocol_path.read_text())
    for key in set(protocol) | set(previous_protocol):
        if key != 'frozen_lanes' and protocol.get(key) != previous_protocol.get(key):
            raise ValueError('build_protocol_changed_before_reviewed_refresh:' + key)
    for lane, old_frozen in previous_protocol['frozen_lanes'].items():
        for key, value in old_frozen.items():
            if key != 'source_diff_sha256' and protocol['frozen_lanes'][lane].get(key) != value:
                raise ValueError('build_frozen_policy_changed:' + lane + ':' + key)
    baseline_spec = json.loads((Path(baseline_worktrees)/'manifest.json').read_text())
    if baseline_spec != original:
        raise ValueError('build_baseline_manifest_identity')
    if set(sources['lanes']) != set(original['lanes']):
        raise ValueError('build_lane_set_changed')
    differences = {}
    for lane, row in sources['lanes'].items():
        old = original['lanes'][lane]
        before = Path(baseline_worktrees)/lane
        after = Path(worktrees)/lane
        for key in set(old) | set(row):
            if key not in ('integration_overlay_files', 'source_diff_sha256', 'composed_file_hashes') and row.get(key) != old.get(key):
                raise ValueError('build_unreviewed_manifest_change:' + lane + ':' + key)
        for name, value in row.get('composed_file_hashes', {}).items():
            if name not in ALLOWED_RUNTIME and old.get('composed_file_hashes', {}).get(name) != value:
                raise ValueError('build_unreviewed_file_hash:' + lane + ':' + name)
        expected = old.get('execution_sha', old['source_sha'])
        for native in (before, after):
            if git('rev-parse', 'HEAD', cwd=native).decode().strip() != expected:
                raise ValueError('build_native_base_changed:' + lane)
        if diff_identity(before) != old['source_diff_sha256']:
            raise ValueError('build_predecessor_not_reproducible:' + lane)
        changed = reviewed_delta(indexed_files(before), indexed_files(after),
                                 ALLOWED_RUNTIME if lane in ('pump', 'meteora') else ())
        differences[lane] = changed
        for rel in row.get('integration_overlay_files', []):
            if (after/rel).read_bytes() != (ROOT/rel).read_bytes():
                raise ValueError('build_overlay_not_current:' + lane + ':' + rel)
        row['source_diff_sha256'] = diff_identity(after)
        refresh_composed_hashes(row, old, after)
        protocol['frozen_lanes'][lane] = dict(
            strategy_version=row['strategy_version'], source_sha=row['source_sha'],
            execution_sha=row.get('execution_sha', row['source_sha']),
            policy_hash=row['policy_hash'], source_diff_sha256=row['source_diff_sha256'])
    for key in set(protocol) | set(previous_protocol):
        if key != 'frozen_lanes' and protocol.get(key) != previous_protocol.get(key):
            raise ValueError('build_economic_protocol_changed:' + key)
    pending = []
    for path, value in ((sources_path, sources), (protocol_path, protocol)):
        temp = path.with_suffix(path.suffix + '.prepared')
        with temp.open('w') as target:
            target.write(json.dumps(value, indent=2) + '\n'); target.flush(); os.fsync(target.fileno())
        pending.append((temp, path))
    for temp, path in pending:
        os.replace(temp, path)
    return dict(passed=True, reviewed_base=REVIEWED_BASE, changes=differences,
                policies_changed=False, market_authority=False,
                publication_requires_single_git_commit=True)


def native_test_collection(native, lane):
    """Collect the exact component suites before any long pressure execution.

    Use the same import precedence and external-network guard as their runner.
    Import errors and empty suites fail closed; no test body is executed here.
    """
    env={k:v for k,v in os.environ.items()
         if k!='PYTHONPATH' and not k.startswith(('MM_','GH_','GITHUB_'))
         and not any(part in k.upper() for part in ('TOKEN','SECRET','PRIVATE_KEY'))}
    with tempfile.TemporaryDirectory(prefix='native-collection-') as td:
        output=Path(td)/'result.json'
        command=[sys.executable,str(ROOT/'certification/offline_tests.py'),
                 '--lane',lane,'--collect-only','--output',str(output)]
        try:
            result=subprocess.run(command,cwd=native,env=env,
                stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL,timeout=60)
            row=json.loads(output.read_text())
            if (result.returncode!=0 or row.get('passed') is not True
                    or row.get('tests_executed')!=0 or row.get('collected_tests',0)<1
                    or row.get('import_errors') or row.get('external_socket_attempts')):
                row['passed']=False
            return row
        except (OSError,ValueError,subprocess.SubprocessError) as exc:
            return dict(passed=False,lane=lane,scope='native_test_collection',
                        error=type(exc).__name__,tests_executed=0)


def verify(worktrees, expected_sha):
    from certification.run import source_integrity, integration_integrity
    from certification.protocol_freeze import verify as protocol_verify
    failures = []; identities = {}
    actual = git('rev-parse', 'HEAD').decode().strip()
    if actual != expected_sha:
        failures.append('build_integration_sha_drift')
    try:
        integration_integrity()
        identities = source_integrity(worktrees)
    except (ValueError, OSError, subprocess.SubprocessError) as exc:
        failures.append(str(exc) if isinstance(exc, ValueError) else type(exc).__name__)
    protocol = protocol_verify()
    failures.extend(protocol['failures'])
    # Reuse the downstream policy contract before starting any pressure replay.
    # Source hashes matching each other must not hide a semantic-policy mismatch.
    from certification.directional_acceptance import policy_contract_checks
    try:
        contracts = policy_contract_checks(json.loads((ROOT/'certification/sources.json').read_text()))
        failures.extend('build_strategy_contract_failed:'+name for name,ok in contracts.items() if not ok)
    except (ValueError, OSError, subprocess.SubprocessError) as exc:
        contracts = {}; failures.append('build_strategy_contract_unavailable:'+type(exc).__name__)
    for rel in FROZEN_PRESSURE:
        if (ROOT/rel).read_bytes() != git('show', REVIEWED_BASE + ':' + rel):
            failures.append('build_pressure_input_changed:' + rel)
    for lane in ('pump', 'meteora'):
        native = (Path(worktrees)/lane).resolve()
        env = dict(os.environ); env.pop('PYTHONPATH', None)
        check = ('import importlib,json; '
                 'names=("meme_machine.solana_evidence_plane",'
                 '"meme_machine.solana_evidence_service",'
                 '"meme_machine.solana_evidence_control",'
                 '"meme_machine.solana_archive_snapshot","meme_machine.solana_checkpoint","meme_machine.solana_retention_outcome"); '
                 'print(json.dumps({n:importlib.import_module(n).__file__ for n in names}))')
        try:
            locations = json.loads(subprocess.check_output(
                [sys.executable, '-c', check], cwd=native, env=env, text=True))
            for name, location in locations.items():
                if Path(location).resolve() != native.joinpath(*name.split('.')).with_suffix('.py'):
                    failures.append('build_import_shadow:' + lane + ':' + name)
        except (ValueError, OSError, subprocess.SubprocessError):
            failures.append('build_native_import_failure:' + lane)
    collections={lane:native_test_collection((Path(worktrees)/lane).resolve(),lane)
                 for lane in ('pump','meteora','pons','ramses')}
    failures.extend('build_native_test_collection_failed:'+lane
                    for lane,row in collections.items() if not row['passed'])
    return dict(passed=not failures, failures=failures, integration_sha=actual,
                native_test_collection=collections,
                source_identities=identities, protocol=protocol, strategy_contracts=contracts,
                pressure_inputs_unchanged=not any(x.startswith('build_pressure_input') for x in failures),
                paper_only=True, market_authority=False)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('operation', choices=('refresh', 'verify'))
    parser.add_argument('--worktrees', required=True)
    parser.add_argument('--baseline-worktrees')
    parser.add_argument('--expected-sha')
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    try:
        if args.operation == 'refresh':
            if not args.baseline_worktrees:
                raise ValueError('build_baseline_required')
            result = refresh(args.worktrees, args.baseline_worktrees)
        else:
            if not args.expected_sha:
                raise ValueError('build_expected_sha_required')
            result = verify(args.worktrees, args.expected_sha)
    except Exception as exc:
        result = dict(passed=False, failures=[str(exc) if isinstance(exc, ValueError) else type(exc).__name__])
    path = Path(args.output); path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(result, indent=2) + '\n')
    print(json.dumps(result, sort_keys=True))
    return 0 if result['passed'] else 1


if __name__ == '__main__':
    raise SystemExit(main())
